name: Setup
description: Setup node and package-manager with cache
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.25.0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'
    - name: Install Dependencies
      run: pnpm install
      shell: bash
